__nextcloud_backup:
  enabled: "{{ nextcloud_backup_enabled }}"
  group: "{{ nextcloud_backup_group }}"
  name: cloud
  repository: "{{ nextcloud_backup_repository }}"
  script_dir: /opt/backup
  user: "{{ nextcloud_backup_user }}"

# __nextcloud_config_file: absolute path to the nextcloud config.php file
__nextcloud_config_file: "{{ __nextcloud_paths.config }}/config.php"

# nextcloud_current_version_path: directory containing the unzipped nextcloud archive for the installed version
__nextcloud_current_version_path: "{{ __nextcloud_paths.versions }}/{{ nextcloud_version }}"

# this is ------- not valid (end sup empty?)

__nextcloud_data_path: "{{ nextcloud_data_path | default([nextcloud_path, 'data'] | join('/')) }}"

# __nextcloud_db_collation:
__nextcloud_db_collation: utf8mb4_general_ci
__nextcloud_db_encoding: utf8mb4

# nextcloud_hash_url: url of the nextcloud archive hash
__nextcloud_digest_url: "{{ __nextcloud_download_url }}.sha256"

# directory containing the web document root for nextcloud
__nextcloud_document_root: "{{ __nextcloud_current_version_path }}"

# nextcloud_download_url: url of the nextcloud archive
__nextcloud_download_url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"

# __nextcloud_paths: Derived directories containing various nextcloud files
# __nextcloud_paths.apps: Directory containing additional installed apps
# __nextcloud_paths.backup: Directory containing nextcloud backups
# __nextcloud_paths.backup_restore: Destination for downloaded snapshots
# __nextcloud_paths.backup_staging: Working directory for creating and uploading backups
# __nextcloud_paths.config: Directory containing nextcloud configuration
# __nextcloud_paths.data: Base directory for all user-generated local data
# __nextcloud_paths.files: Directory containing nextcloud files
# __nextcloud_paths.versions: Directory containing expanded nextcloud archives ready to be deployed
# __nextcloud_paths.work: Working directory for temp files
__nextcloud_paths:
  apps: "{{ __nextcloud_data_path }}/apps"
  backup: "{{ nextcloud_backup_path | default([nextcloud_path, 'backup'] | join('/')) }}"
  backup_restore: "{{ nextcloud_backup_path | default([nextcloud_path, 'backup'] | join('/')) }}/restore"
  backup_staging: "{{ nextcloud_backup_path | default([nextcloud_path, 'backup'] | join('/')) }}/staging"
  config: "{{ __nextcloud_data_path }}/config"
  data: "{{ __nextcloud_data_path }}"
  files: "{{ __nextcloud_data_path }}/files"
  versions: "{{ nextcloud_path }}/versions"
  work: "{{ nextcloud_path }}/.work"

__nextcloud_php_packages:
  common:
    # needed for proper svg support
    # - libmagickcore-6.q16-6-extra=8:{{ nextcloud_libmagickcore_extra_version }}*
    - php{{ php_version }}-apcu
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-bz2
    - php{{ php_version }}-cli
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-gmp
    # - php-imagick={{ nextcloud_imagick_version }}*
    - php{{ php_version }}-intl
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip
  fpm: php{{ php_version }}-fpm
  mysql: php{{ php_version }}-mysql
  sqlite3: php{{ php_version }}-sqlite3

# __nextcloud_rclone_configs: list of rclone configs to be installed; see https://github.com/stefangweichinger/ansible-rclone
__nextcloud_rclone_configs:
  - name: backblaze-b2
    properties:
      type: b2
      account: "{{ nextcloud_backblaze_b2_account }}"
      key: "{{ nextcloud_backblaze_b2_key }}"

# __nextcloud_static_packages: packages which are always installed, in addition to extra packages
__nextcloud_static_packages: ["bzip2", "ffmpeg"]

# todo: update this to work even if we change php versions...
__nextcloud_php_ini_path: /etc/php/{{ php_version }}/apache2/php.ini
