---
- name: (BACKUP) Set pre_backup_cmd if a "before" hook was specified
  ansible.builtin.set_fact:
    __backup_default_item: "{{ __backup_default_item | combine({ 'pre_backup_cmd': backup_before_hook }) }}"
  when: backup_before_hook is defined
- name: (BACKUP) Set monitoring_call if an "after" hook was specified
  ansible.builtin.set_fact:
    __backup_default_item: "{{ __backup_default_item | combine({ 'monitoring_call': backup_after_hook }) }}"
  when: backup_after_hook is defined

- name: (BACKUP) Merge defaults into backup configurations
  ansible.builtin.set_fact:
    __backup_configs_with_defaults: >-
      {{
        __backup_configs_with_defaults | default([]) + [
          item | combine(__backup_default_item)
        ]
      }}
  loop: "{{ __backup_configs }}"

- name: Display __backup_repository_configs
  ansible.builtin.debug:
    msg: '{{ __backup_repository_configs }}'

- name: Display __backup_configs_with_defaults
  ansible.builtin.debug:
    msg: '{{ __backup_configs_with_defaults }}'

- name: (BACKUP) Install and configure restic
  ansible.builtin.include_role:
    name: local.pegasuspad.restic
  vars:
    restic_backups: '{{ __backup_configs_with_defaults }}'
    restic_create_schedule: true
    restic_dir_group: '{{ backup_group }}'
    restic_dir_owner: '{{ backup_user }}'
    restic_download_path: '{{ backup_script_dir }}'
    restic_no_log: '{{ backup_no_log }}'
    restic_repos: '{{ __backup_repository_configs }}'
    restic_script_dir: '{{ backup_script_dir }}'
    restic_version: '{{ backup_restic_version }}'
  when: backup_enabled
