---
- name: (BACKUP) Set pre_backup_cmd if a "before" hook was specified
  ansible.builtin.set_fact:
    __backup_default_item: "{{ __backup_default_item | combine({ 'pre_backup_cmd': backup_hook_before }) }}"
  when: backup_hook_before is defined
- name: (BACKUP) Set monitoring_call if an "after" hook was specified
  ansible.builtin.set_fact:
    __backup_default_item: "{{ __backup_default_item | combine({ 'monitoring_call': backup_hook_after }) }}"
  when: backup_hook_after is defined

- name: Display __backup_default_item
  ansible.builtin.debug:
    msg: '{{ __backup_default_item }}'
- name: Display list of all backups
  ansible.builtin.debug:
    msg: '{{ [__backup_default_item] + backup_extra_backups }}'

- name: (BACKUP) Install and configure restic
  ansible.builtin.include_role:
    name: local.pegasuspad.restic
  vars:
    restic_backups: '{{ [__backup_default_item] + backup_extra_backups }}'
    restic_create_schedule: true
    restic_dir_group: '{{ backup_group }}'
    restic_dir_owner: '{{ backup_user }}'
    restic_download_path: '{{ backup_script_dir }}'
    restic_no_log: '{{ backup_no_log }}'
    restic_repos: '{{ __backup_repo_list | items2dict }}'
    restic_script_dir: '{{ backup_script_dir }}'
    restic_version: '{{ backup_restic_version }}'
  when: backup_enabled is defined