- name: Install backup and restore scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0744"
  with_fileglob:
    - "usr/local/bin/*"

- name: Perform nightly backups
  become: true
  ansible.builtin.cron:
    hour: "7" # 2am central
    job: /usr/local/bin/cronjob-lock /usr/local/bin/backup >>{{ nextcloud_logfile }} 2>&1
    minute: "2"
    name: "backup nextcloud nightly"
    state: present
    user: "root"
