---
- name: (BACKUP) Install backup staging script
  ansible.builtin.template:
    src: "/usr/local/bin/stage-backup"
    dest: '/usr/local/bin'
    owner: root
    group: root
    # this file contain credentials, so only allow root to read them
    mode: "0700"

- name: (BACKUP) Install and configure backup utilities
  ansible.builtin.include_role:
    name: local.pegasuspad.backup
  vars:
    backup_before_hook: '/usr/local/bin/stage-backup'
    backup_extra_tags: ['v{{ nextcloud_version }}']
    backup_source_path: '{{ __nextcloud_paths.backup_staging }}'
