---
- name: Install Nextcloud
  tags: [nextcloud]
  ansible.builtin.import_tasks: base_install.yml

- name: Configure Nextcloud
  tags: [nextcloud]
  ansible.builtin.import_tasks: base_configure.yml

- name: Configure FPM
  tags: [nextcloud]
  ansible.builtin.import_tasks: fpm.yml
  when: nextcloud_use_fpm
