---
#
# Required Inputs:
#   - backup_snapshot_id: ID of the snapshot to restore.
#
# Optional Inputs:
#   -  backup_repository_name: Name of the repository from which to restore a snapshot. [nextcloud_backup_repository_name]
#

- name: (RESTORE) Verify required parameters are set
  ansible.builtin.assert:
    fail_msg: Snapshot download request is invalid.
    that:
      - backup_snapshot_id is defined
      - backup_snapshot_id | length > 0

- name: (RESTORE) Invoke backup role's download-snapshot tasks
  include_role:
    name: local.pegasuspad.backup
    tasks_from: actions/download-snapshot.yml
  vars:
    backup_repository_name: '{{ backup_repository_name | default(nextcloud_backup_repository_name) }}'
    backup_restore_path: '{{ __nextcloud_paths.backup_restore }}/{{ backup_snapshot_id }}'
