---
- name: restart apache
  service: name=apache2 state=restarted
- name: restart php-fpm
  service: name=php{{ php_version }}-fpm state=restarted
- name: disable maintenance mode
  ansible.builtin.template:
    src: maintenance.config.php.j2
    dest: "{{ __nextcloud_paths.config }}/maintenance.config.php"
    group: www-data
    mode: "0770"
    owner: www-data
  vars:
    nextcloud_maintenance_mode: false