---
- name: Install fpm package
  ansible.builtin.apt:
    pkg: "{{ __nextcloud_php_packages.fpm }}"
    state: present

# configure php-fpm pool configuration
- name: Ensure php-fpm pool config directory
  ansible.builtin.file:
    group: root
    mode: "0644"
    owner: root
    path: "/etc/php/{{ php_version }}/fpm/pool.d"
    state: directory
- name: Create php-fpm pool configuration
  become: true
  ansible.builtin.template:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    group: root
    mode: "0644"
    owner: root
    src: etc/php/8.x/fpm/pool.d/www.conf.j2
  notify: restart php-fpm