---
- name: restart apache
  service: name=apache2 state=restarted
- name: restart php-fpm
  service: name=php{{ php_version }}-fpm state=restarted
- name: disable maintenance mode
  ansible.builtin.shell:
    cmd: sudo -u www-data php "{{ __nextcloud_current_version_path }}/occ" maintenance:mode --no-ansi --off
