# temp variable used to build __backup_repo_list
__backup_default_repository_item:
  key: '{{ backup_repository_name }}'
  value: '{{ backup_repository }}'
# list of all backup repositories, including the default and extra ones
__backup_repo_list: '{{ [__backup_default_repository_item] + backup_extra_repositories }}'

# temp variable used to build __backup_backup_list
__backup_default_item:
  niceness: '{{ backup_niceness }}'
  src: '{{ backup_path }}'
  tags: '{{ backup_extra_tags }}'
