# temp variable used to build __backup_repo_list
__backup_default_repository_item:
  - key: '{{ backup_repository_name }}'
    value: '{{ backup_repository }}'
# list of all backup repositories, including the default and extra ones
__backup_repo_list: '{{ __backup_default_repository_item + backup_extra_repositories }}'

# temp variable used to build __backup_backup_list
__backup_default_item:
  - monitoring_call: '{{ backup_hook_after }}'
    name: '{{ backup_repository_name }}'
    niceness: '{{ backup_niceness }}'
    pre_backup_cmd: '{{ backup_hook_before }}'
    repo: '{{ backup_repository_name }}'
    schedule_oncalendar: '{{ backup_schedule }}'
    scheduled: '{{ backup_schedule_enabled }}'
    src: '{{ backup_source_path }}'
    tags: '{{ backup_extra_tags }}'
# list of all backup configurations, including the default and extra ones
__backup_backup_list: '{{ __backup_default_item + backup_extra_backups }}'