---
- name: (CONFIGURE) Determine current maintenance mode state
  ansible.builtin.shell:
    cmd: sudo -u www-data php "{{ __nextcloud_current_version_path }}/occ" maintenance:mode --no-ansi
  changed_when: False
  register: maintenance_mode_result

- name: "(CONFIGURE) Set maintenance mode using occ"
  ansible.builtin.shell:
    cmd: sudo -u www-data php "{{ __nextcloud_current_version_path }}/occ" maintenance:mode --no-ansi --on
  notify:
    - disable maintenance mode
  when: maintenance_mode_result is search("disabled")
