---

# Variables:
#   - nextcloud_maintenance_mode: the mode to set, true or false

- name: "(CONFIGURE) Set maintenance mode using occ"
  ansible.builtin.shell:
    cmd: sudo -u www-data php "{{ __nextcloud_current_version_path }}/occ" maintenance:mode --no-ansi "{{ mode_flag }}"
  vars:
    mode_flag: "{{ '--on' if nextcloud_maintenance_mode else '--off' }}"
