---
# php_ini: Dictionary containing php.ini directives and values to apply to the local configuration. [no custom configuration]
php_ini: {}

# php_packages: A list of the PHP packages to install. ('php' is always included by default.) [Empty list]
php_packages: []

# php_version: "<Major>.<Minor>" Version string for the php packages to install. May contain wildcards. [8.3]
php_version: "8.3"
